"use client"

import AuthenticationContext from "@/contexts/AuthenticationContext";
import { useContext } from "react";

export default function Home() {
  const {isAuthenticated, checkAuthentication} = useContext(AuthenticationContext)
  
  checkAuthentication()

  return (
    <main>
      <h1>Campeonato Municipal</h1>
      <p>Generated by create next app</p>
    </main>
  );
}
