on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: Install client dependencies
      run: |
        cd client
        npm ci

    - name: Install server dependencies
      run: |
        cd server
        npm ci

    - name: Install root dependencies
      run: |
        npm ci

    - name: Run server
      run: |
        npm run action-server &

    - name: Wait for server to start
      run: |
        until $(curl --output /dev/null --silent --head --fail http://localhost:5000/health); do
          printf '.'
          sleep 5
        done

    - name: Run tests
      run: |
        npm ci
        npm test

    - name: Lint root
      run: |
        npm run lint